version: '3.7'

services:

  web:
    build: .
    ports:
      - ${PORT}:80
      - ${WEBSOCKET_SERVER_PORT}:9000
    expose:
      - 9000
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - YII_ENV=${YII_ENV}

    volumes:
      # Re-use local composer cache via host volume
      - composer-cache:/root/.composer/cache:delegated
      # Mount source code
      - ./../:/app
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - carwow-network

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped
    networks:
      - carwow-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_HOST=${MYSQL_HOST}
      - UPLOAD_LIMIT=512M
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - carwow-network

volumes:
  composer-cache:
networks:
  carwow-network:
    name: carwow-network
    driver: bridge
name: carwow
